name: mokkoji_app
description: Mokkoji MVP - 일정/모임 통합 브리핑 앱
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  video_player: ^2.8.6
  flutter_riverpod: ^2.5.1
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4

  # 로컬라이제이션
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  sqflite_common_ffi: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/mokkoji_icon.jpg
    - assets/videos/Onboarding_Illustration_Generation_First.mp4
    - assets/videos/Onboarding_Illustration_Generation_Second.mp4
    - assets/videos/Generating_Onboarding_Illustration_Third.mp4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/mokkoji_icon.png"
  adaptive_icon_background: "#FF6B6B"
  adaptive_icon_foreground: "assets/icons/mokkoji_icon.png"
